# Generated by Django 3.2.8 on 2021-10-19 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone', models.TextField(verbose_name='Номер телефона')),
                ('address', models.TextField(verbose_name='Адрес кинотеатра')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Название фильма')),
                ('description', models.TimeField(verbose_name='Описание')),
                ('release_date', models.DateField(verbose_name='Год выпуска')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('duration', models.TimeField(verbose_name='Продолжительность фильма')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер зала')),
                ('count_seats', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cinema', verbose_name='Кинотеар')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Место')),
                ('available', models.BooleanField(verbose_name='Свобдно')),
                ('hall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.hall', verbose_name='Зал')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city', verbose_name='Город'),
        ),
    ]
