# Generated by Django 3.2.8 on 2021-10-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211020_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='duration',
            field=models.CharField(max_length=255, verbose_name='Продолжительность фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.CharField(max_length=255, verbose_name='Год выпуска'),
        ),
    ]
